# Generated by Django 4.1.7 on 2023-03-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todo',
            new_name='Task',
        ),
    ]
